id: IC8DC0A2E
ocr_import_info:
  timestamp: '2023-10-06T15:22:15.156078+00:00'
  batch_id: batch-2caf
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 19:29:44.483747+00:00
last_modified: 2023-10-06 19:29:44.483754+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN22337
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN22337
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་གདམས་གླེགས་བམ།
  languages:
  - bo
  author: རྔོག་ལོ་ཆུང་ལེགས་པའི་ཤེས་རབ།
statistics:
  ocr_word_mean_confidence_index: 0.9775577595181285
  ocr_word_median_confidence_index: 0.999913
bases:
  I4CN10003:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CN10003
      total_pages: 812
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4CN10003.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999384
      ocr_word_mean_confidence_index: 0.978625937185592
  I4CN10002:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CN10002
      total_pages: 904
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CN10002.txt
    statistics:
      ocr_word_median_confidence_index: 0.99988073
      ocr_word_mean_confidence_index: 0.9765369876434652
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
